import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { z, type ZodType } from 'zod';

import { createCatalogManifest, DEFAULT_SOURCE_ROOT } from './manifest.js';

export const CATALOG_COLLECTIONS = [
  'race',
  'subrace',
  'background',
  'feat',
  'optionalfeature',
  'facility',
  'spell',
  'action',
  'condition',
  'disease',
  'status',
  'language',
  'languageScript',
  'object',
  'trap',
  'hazard',
  'deity',
  'table',
  'monster',
  'item',
  'itemGroup',
  'itemBase',
  'itemProperty',
  'itemType',
  'itemTypeAdditionalEntries',
  'itemEntry',
  'itemMastery',
  'vehicle',
  'vehicleUpgrade',
  'class',
  'subclass',
  'classFeature',
  'subclassFeature',
] as const;

export type CatalogCollection = (typeof CATALOG_COLLECTIONS)[number];

export interface ValidationFailure {
  readonly collection: CatalogCollection;
  readonly file: string;
  readonly path: readonly PropertyKey[];
  readonly recordName?: string | undefined;
  readonly recordSource?: string | undefined;
  readonly message: string;
}

export class ValidationError extends Error {
  constructor(readonly failures: readonly ValidationFailure[]) {
    super(
      failures
        .map((failure) => `${failure.file} ${failure.collection} ${failure.path.join('.')}: ${failure.message}`)
        .join('\n'),
    );
    this.name = 'ValidationError';
  }
}

export interface ValidationResult {
  readonly files: readonly string[];
}

type RawRecord = Readonly<Record<string, unknown>>;

const JSON_VALUE_SCHEMA: ZodType<unknown> = z.json();
const ENTRY_SCHEMA: ZodType<unknown> = z.lazy(() =>
  z.union([
    z.string(),
    z
      .object({
        attributes: JSON_VALUE_SCHEMA.optional(),
        by: JSON_VALUE_SCHEMA.optional(),
        caption: JSON_VALUE_SCHEMA.optional(),
        classFeature: JSON_VALUE_SCHEMA.optional(),
        colLabels: JSON_VALUE_SCHEMA.optional(),
        colStyles: JSON_VALUE_SCHEMA.optional(),
        columns: JSON_VALUE_SCHEMA.optional(),
        consumes: JSON_VALUE_SCHEMA.optional(),
        count: JSON_VALUE_SCHEMA.optional(),
        credit: JSON_VALUE_SCHEMA.optional(),
        data: JSON_VALUE_SCHEMA.optional(),
        entries: z.array(ENTRY_SCHEMA).optional(),
        entry: JSON_VALUE_SCHEMA.optional(),
        feat: JSON_VALUE_SCHEMA.optional(),
        footnotes: JSON_VALUE_SCHEMA.optional(),
        genTables: JSON_VALUE_SCHEMA.optional(),
        href: JSON_VALUE_SCHEMA.optional(),
        id: JSON_VALUE_SCHEMA.optional(),
        isRequiredOption: JSON_VALUE_SCHEMA.optional(),
        items: z.array(ENTRY_SCHEMA).optional(),
        name: z.string().optional(),
        optionalfeature: JSON_VALUE_SCHEMA.optional(),
        overwrite: JSON_VALUE_SCHEMA.optional(),
        page: JSON_VALUE_SCHEMA.optional(),
        prerequisite: JSON_VALUE_SCHEMA.optional(),
        preserve: JSON_VALUE_SCHEMA.optional(),
        reprintedAs: JSON_VALUE_SCHEMA.optional(),
        rows: JSON_VALUE_SCHEMA.optional(),
        source: JSON_VALUE_SCHEMA.optional(),
        style: JSON_VALUE_SCHEMA.optional(),
        subclassFeature: JSON_VALUE_SCHEMA.optional(),
        tableInclude: JSON_VALUE_SCHEMA.optional(),
        tag: JSON_VALUE_SCHEMA.optional(),
        type: z.string(),
      })
      .strict(),
  ]),
);
const REQUIRED_STRING_FIELDS = new Set([
  'source',
  'className',
  'classSource',
  'pantheon',
  'subclassShortName',
  'subclassSource',
]);
const NUMBER_FIELDS = new Set(['page', 'header', 'blindsight', 'darkvision']);
const ARRAY_FIELDS = new Set(['additionalEntries', 'entries']);
const OBJECT_FIELDS = new Set(['_copy', 'overwrite']);

const COLLECTION_FIELDS: Readonly<Record<CatalogCollection, readonly string[]>> = {
  race: [
    '_copy',
    '_versions',
    'ability',
    'additionalSources',
    'additionalSpells',
    'age',
    'alias',
    'armorProficiencies',
    'basicRules',
    'basicRules2024',
    'blindsight',
    'conditionImmune',
    'creatureTypeTags',
    'creatureTypes',
    'darkvision',
    'edition',
    'entries',
    'feats',
    'hasFluff',
    'hasFluffImages',
    'heightAndWeight',
    'immune',
    'languageProficiencies',
    'lineage',
    'name',
    'otherSources',
    'page',
    'reprintedAs',
    'resist',
    'size',
    'sizeEntry',
    'skillProficiencies',
    'soundClip',
    'source',
    'speed',
    'srd',
    'srd52',
    'toolProficiencies',
    'traitTags',
    'vulnerable',
    'weaponProficiencies',
  ],
  subrace: [
    '_copy',
    '_versions',
    'ability',
    'additionalSpells',
    'age',
    'alias',
    'armorProficiencies',
    'basicRules',
    'darkvision',
    'entries',
    'feats',
    'hasFluff',
    'hasFluffImages',
    'heightAndWeight',
    'languageProficiencies',
    'name',
    'otherSources',
    'overwrite',
    'page',
    'raceName',
    'raceSource',
    'reprintedAs',
    'resist',
    'skillProficiencies',
    'skillToolLanguageProficiencies',
    'soundClip',
    'source',
    'speed',
    'srd',
    'toolProficiencies',
    'traitTags',
    'weaponProficiencies',
  ],
  background: [
    '_copy',
    'ability',
    'additionalSources',
    'additionalSpells',
    'basicRules',
    'basicRules2024',
    'edition',
    'entries',
    'feats',
    'fromFeature',
    'hasFluff',
    'hasFluffImages',
    'languageProficiencies',
    'name',
    'otherSources',
    'page',
    'prerequisite',
    'reprintedAs',
    'skillProficiencies',
    'skillToolLanguageProficiencies',
    'source',
    'srd',
    'srd52',
    'startingEquipment',
    'toolProficiencies',
  ],
  feat: [
    '_versions',
    'ability',
    'additionalSources',
    'additionalSpells',
    'armorProficiencies',
    'basicRules2024',
    'bonusSenses',
    'category',
    'conditionImmune',
    'entries',
    'expertise',
    'hasFluffImages',
    'immune',
    'languageProficiencies',
    'name',
    'optionalfeatureProgression',
    'page',
    'prerequisite',
    'repeatable',
    'repeatableHidden',
    'reprintedAs',
    'resist',
    'savingThrowProficiencies',
    'senses',
    'skillProficiencies',
    'skillToolLanguageProficiencies',
    'source',
    'srd',
    'srd52',
    'toolProficiencies',
    'traitTags',
    'weaponProficiencies',
  ],
  optionalfeature: [
    'additionalSpells',
    'consumes',
    'entries',
    'featProgression',
    'featureType',
    'hasFluffImages',
    'isClassFeatureVariant',
    'name',
    'optionalfeatureProgression',
    'otherSources',
    'page',
    'prerequisite',
    'reprintedAs',
    'senses',
    'skillProficiencies',
    'source',
    'srd',
    'srd52',
  ],
  facility: [
    'entries',
    'facilityType',
    'hasFluffImages',
    'hirelings',
    'level',
    'name',
    'orders',
    'page',
    'prerequisite',
    'source',
    'space',
  ],
  spell: [
    'abilityCheck',
    'additionalSources',
    'affectsCreatureType',
    'alias',
    'areaTags',
    'basicRules',
    'basicRules2024',
    'components',
    'conditionImmune',
    'conditionInflict',
    'damageImmune',
    'damageInflict',
    'damageResist',
    'damageVulnerable',
    'duration',
    'entries',
    'entriesHigherLevel',
    'hasFluff',
    'hasFluffImages',
    'level',
    'meta',
    'miscTags',
    'name',
    'otherSources',
    'page',
    'range',
    'referenceSources',
    'reprintedAs',
    'savingThrow',
    'scalingLevelDice',
    'school',
    'source',
    'spellAttack',
    'srd',
    'srd52',
    'time',
  ],
  action: [
    'basicRules',
    'basicRules2024',
    'entries',
    'fromVariant',
    'name',
    'page',
    'reprintedAs',
    'seeAlsoAction',
    'source',
    'srd',
    'srd52',
    'time',
  ],
  condition: [
    'basicRules',
    'basicRules2024',
    'entries',
    'hasFluffImages',
    'name',
    'otherSources',
    'page',
    'reprintedAs',
    'source',
    'srd',
    'srd52',
  ],
  disease: ['entries', 'name', 'page', 'reprintedAs', 'source', 'srd', 'srd52', 'type'],
  status: ['basicRules', 'basicRules2024', 'entries', 'name', 'page', 'reprintedAs', 'source', 'srd', 'srd52'],
  language: [
    'additionalSources',
    'basicRules',
    'basicRules2024',
    'dialects',
    'entries',
    'fonts',
    'hasFluffImages',
    'name',
    'origin',
    'otherSources',
    'page',
    'reprintedAs',
    'script',
    'source',
    'srd',
    'srd52',
    'type',
    'typicalSpeakers',
  ],
  languageScript: ['fonts', 'name', 'source'],
  object: [
    'ac',
    'actionEntries',
    'altArt',
    'cha',
    'con',
    'conditionImmune',
    'dex',
    'entries',
    'hasFluffImages',
    'hasToken',
    'hp',
    'immune',
    'int',
    'isNpc',
    'name',
    'objectType',
    'page',
    'reprintedAs',
    'resist',
    'senses',
    'size',
    'source',
    'speed',
    'srd',
    'str',
    'token',
    'tokenCredit',
    'tokenCustom',
    'vulnerable',
    'wis',
  ],
  trap: [
    'countermeasures',
    'duration',
    'eActive',
    'eConstant',
    'eDynamic',
    'effect',
    'entries',
    'hasFluffImages',
    'hauntBonus',
    'initiative',
    'initiativeNote',
    'name',
    'page',
    'rating',
    'reprintedAs',
    'source',
    'srd',
    'srd52',
    'trapHazType',
    'trigger',
  ],
  hazard: [
    'entries',
    'hasFluffImages',
    'name',
    'otherSources',
    'page',
    'rating',
    'reprintedAs',
    'source',
    'trapHazType',
  ],
  deity: [
    '_copy',
    'additionalSources',
    'alignment',
    'altNames',
    'basicRules',
    'category',
    'customExtensionOf',
    'domains',
    'entries',
    'name',
    'page',
    'pantheon',
    'piety',
    'plane',
    'province',
    'reprintAlias',
    'source',
    'srd',
    'symbol',
    'symbolImg',
    'title',
    'worshipers',
  ],
  table: ['basicRules', 'caption', 'colLabels', 'colStyles', 'name', 'otherSources', 'page', 'rows', 'source', 'srd'],
  monster: [
    '_copy',
    '_versions',
    'ac',
    'action',
    'actionNote',
    'actionTags',
    'alias',
    'alignment',
    'alignmentPrefix',
    'altArt',
    'attachedItems',
    'basicRules',
    'basicRules2024',
    'bonus',
    'cha',
    'con',
    'conditionImmune',
    'conditionInflict',
    'conditionInflictLegendary',
    'conditionInflictSpell',
    'cr',
    'damageTags',
    'damageTagsLegendary',
    'damageTagsSpell',
    'dex',
    'dragonAge',
    'dragonCastingColor',
    'environment',
    'familiar',
    'foundryTokenScale',
    'gear',
    'group',
    'hasFluff',
    'hasFluffImages',
    'hasToken',
    'hp',
    'immune',
    'initiative',
    'int',
    'isNamedCreature',
    'isNpc',
    'isReprinted',
    'languageTags',
    'languages',
    'legendary',
    'legendaryActions',
    'legendaryActionsLair',
    'legendaryGroup',
    'legendaryHeader',
    'level',
    'miscTags',
    'mythic',
    'mythicHeader',
    'name',
    'otherSources',
    'page',
    'passive',
    'pbNote',
    'reaction',
    'reactionHeader',
    'reactionNote',
    'referenceSources',
    'reprintedAs',
    'resist',
    'save',
    'savingThrowForced',
    'savingThrowForcedLegendary',
    'savingThrowForcedSpell',
    'senseTags',
    'senses',
    'shortName',
    'size',
    'sizeNote',
    'skill',
    'soundClip',
    'source',
    'speed',
    'spellcasting',
    'spellcastingTags',
    'srd',
    'srd52',
    'str',
    'summonedByClass',
    'summonedBySpell',
    'summonedBySpellLevel',
    'tokenCredit',
    'tokenCustom',
    'trait',
    'traitTags',
    'treasure',
    'type',
    'variant',
    'vulnerable',
    'wis',
  ],
  item: [
    '_copy',
    'ability',
    'ac',
    'additionalEntries',
    'additionalSources',
    'age',
    'alias',
    'ammoType',
    'atomicPackContents',
    'attachedSpells',
    'barDimensions',
    'baseItem',
    'basicRules',
    'basicRules2024',
    'bonusAbilityCheck',
    'bonusAc',
    'bonusProficiencyBonus',
    'bonusSavingThrow',
    'bonusSavingThrowConcentration',
    'bonusSpellAttack',
    'bonusSpellSaveDc',
    'bonusWeapon',
    'bonusWeaponAttack',
    'bonusWeaponDamage',
    'capCargo',
    'capPassenger',
    'carryingCapacity',
    'charges',
    'classFeatures',
    'conditionImmune',
    'containerCapacity',
    'crew',
    'crewMax',
    'crewMin',
    'critThreshold',
    'curse',
    'detail1',
    'detail2',
    'dexterityMax',
    'dmg1',
    'dmg2',
    'dmgType',
    'entries',
    'firearm',
    'focus',
    'grantsLanguage',
    'grantsProficiency',
    'group',
    'hasFluff',
    'hasFluffImages',
    'hasRefs',
    'immune',
    'light',
    'lootTables',
    'mastery',
    'miscTags',
    'modifySpeed',
    'name',
    'optionalfeatures',
    'otherSources',
    'packContents',
    'page',
    'poison',
    'poisonTypes',
    'property',
    'range',
    'rarity',
    'recharge',
    'rechargeAmount',
    'referenceSources',
    'reprintedAs',
    'reqAttune',
    'reqAttuneAlt',
    'reqAttuneTags',
    'resist',
    'scfType',
    'seeAlsoDeck',
    'seeAlsoVehicle',
    'sentient',
    'shippingCost',
    'source',
    'speed',
    'spellScrollLevel',
    'srd',
    'srd52',
    'staff',
    'stealth',
    'strength',
    'tattoo',
    'tier',
    'travelCost',
    'type',
    'typeAlt',
    'value',
    'valueRarity',
    'vehAc',
    'vehDmgThresh',
    'vehHp',
    'vehSpeed',
    'vulnerable',
    'weaponCategory',
    'weight',
    'weightNote',
    'wondrous',
  ],
  itemGroup: [
    'ability',
    'ac',
    'attachedSpells',
    'baseItem',
    'basicRules',
    'basicRules2024',
    'bonusAc',
    'bonusWeapon',
    'charges',
    'classFeatures',
    'conditionImmune',
    'curse',
    'dmg1',
    'dmg2',
    'dmgType',
    'entries',
    'focus',
    'grantsProficiency',
    'hasFluff',
    'hasFluffImages',
    'hasRefs',
    'items',
    'itemsHidden',
    'light',
    'lootTables',
    'mastery',
    'miscTags',
    'modifySpeed',
    'name',
    'otherSources',
    'page',
    'property',
    'range',
    'rarity',
    'recharge',
    'rechargeAmount',
    'referenceSources',
    'reprintedAs',
    'reqAttune',
    'reqAttuneTags',
    'resist',
    'scfType',
    'sentient',
    'source',
    'srd',
    'srd52',
    'staff',
    'stealth',
    'strength',
    'tattoo',
    'tier',
    'type',
    'weaponCategory',
    'weight',
    'wondrous',
  ],
  itemBase: [
    'ac',
    'additionalEntries',
    'additionalSources',
    'age',
    'alias',
    'ammoType',
    'armor',
    'arrow',
    'axe',
    'basicRules',
    'basicRules2024',
    'bolt',
    'bow',
    'bulletFirearm',
    'bulletSling',
    'cellEnergy',
    'club',
    'crossbow',
    'dagger',
    'dmg1',
    'dmg2',
    'dmgType',
    'edition',
    'entries',
    'firearm',
    'group',
    'hammer',
    'hasFluff',
    'hasFluffImages',
    'lance',
    'mace',
    'mastery',
    'miscTags',
    'name',
    'needleBlowgun',
    'net',
    'packContents',
    'page',
    'polearm',
    'property',
    'range',
    'rapier',
    'rarity',
    'referenceSources',
    'reload',
    'reprintedAs',
    'scfType',
    'source',
    'spear',
    'srd',
    'srd52',
    'staff',
    'stealth',
    'strength',
    'sword',
    'type',
    'value',
    'valueRarity',
    'weapon',
    'weaponCategory',
    'weight',
  ],
  itemProperty: ['abbreviation', 'basicRules2024', 'entries', 'name', 'page', 'reprintedAs', 'source', 'template'],
  itemType: ['_copy', 'abbreviation', 'basicRules2024', 'entries', 'name', 'page', 'reprintedAs', 'source'],
  itemTypeAdditionalEntries: ['appliesTo', 'entries', 'name', 'source'],
  itemEntry: ['entriesTemplate', 'name', 'source'],
  itemMastery: ['basicRules2024', 'entries', 'name', 'page', 'source', 'srd52'],
  vehicle: [
    'ac',
    'action',
    'actionStation',
    'actionThresholds',
    'capCargo',
    'capCreature',
    'capCrew',
    'capCrewNote',
    'capPassenger',
    'cha',
    'con',
    'conditionImmune',
    'control',
    'cost',
    'dex',
    'dimensions',
    'entries',
    'hasFluff',
    'hasFluffImages',
    'hasToken',
    'hp',
    'hull',
    'immune',
    'int',
    'movement',
    'name',
    'otherSources',
    'pace',
    'page',
    'reaction',
    'reprintedAs',
    'size',
    'source',
    'speed',
    'srd',
    'station',
    'str',
    'terrain',
    'tokenCredit',
    'tokenCustom',
    'trait',
    'type',
    'vehicleType',
    'weapon',
    'weight',
    'wis',
  ],
  vehicleUpgrade: ['entries', 'name', 'page', 'source', 'upgradeType'],
  class: [
    'additionalSpells',
    'basicRules',
    'basicRules2024',
    'cantripProgression',
    'casterProgression',
    'classFeatures',
    'classTableGroups',
    'edition',
    'featProgression',
    'hasFluff',
    'hasFluffImages',
    'hd',
    'isSidekick',
    'multiclassing',
    'name',
    'optionalfeatureProgression',
    'otherSources',
    'page',
    'preparedSpells',
    'preparedSpellsChange',
    'preparedSpellsProgression',
    'primaryAbility',
    'proficiency',
    'reprintedAs',
    'source',
    'spellcastingAbility',
    'spellsKnownProgression',
    'spellsKnownProgressionFixed',
    'spellsKnownProgressionFixedAllowLowerLevel',
    'spellsKnownProgressionFixedByLevel',
    'srd',
    'srd52',
    'startingEquipment',
    'startingProficiencies',
    'subclassTitle',
  ],
  subclass: [
    '_copy',
    'additionalSpells',
    'basicRules',
    'basicRules2024',
    'cantripProgression',
    'casterProgression',
    'className',
    'classSource',
    'edition',
    'featProgression',
    'fluff',
    'hasFluff',
    'hasFluffImages',
    'isReprinted',
    'name',
    'optionalfeatureProgression',
    'otherSources',
    'page',
    'preparedSpellsChange',
    'preparedSpellsProgression',
    'reprintedAs',
    'shortName',
    'source',
    'spellcastingAbility',
    'spellsKnownProgression',
    'srd',
    'srd52',
    'subclassFeatures',
    'subclassTableGroups',
  ],
  classFeature: [
    'basicRules',
    'basicRules2024',
    'className',
    'classSource',
    'consumes',
    'entries',
    'header',
    'isClassFeatureVariant',
    'level',
    'name',
    'otherSources',
    'page',
    'source',
    'srd',
    'srd52',
    'type',
  ],
  subclassFeature: [
    '_copy',
    'basicRules',
    'basicRules2024',
    'className',
    'classSource',
    'consumes',
    'entries',
    'header',
    'isClassFeatureVariant',
    'level',
    'name',
    'otherSources',
    'page',
    'source',
    'srd',
    'srd52',
    'subclassShortName',
    'subclassSource',
    'type',
  ],
};

function getFieldSchema(collection: CatalogCollection, field: string): ZodType<unknown> {
  if (field === 'name')
    return collection === 'subrace' || collection === 'itemProperty' ? z.string().optional() : z.string();
  if (field === 'abbreviation' && collection === 'itemProperty') return z.string();
  if (field === 'pantheon' && collection === 'deity') return z.string();
  if (collection === 'table' && field === 'caption') return z.string().optional();
  if (collection === 'table' && (field === 'colLabels' || field === 'colStyles'))
    return z.array(JSON_VALUE_SCHEMA).optional();
  if (collection === 'table' && field === 'rows') return z.array(z.array(JSON_VALUE_SCHEMA));
  if (REQUIRED_STRING_FIELDS.has(field)) return z.string();
  if (field === 'raceName' || field === 'raceSource') return z.string().optional();
  if (field === 'level') {
    return collection === 'classFeature' || collection === 'subclassFeature' ? z.number() : z.number().optional();
  }
  if (NUMBER_FIELDS.has(field)) return z.number().optional();
  if (ARRAY_FIELDS.has(field)) return z.array(ENTRY_SCHEMA).optional();
  if (OBJECT_FIELDS.has(field)) return z.object({}).catchall(JSON_VALUE_SCHEMA).optional();
  return JSON_VALUE_SCHEMA.optional();
}

function createRecordSchema(collection: CatalogCollection): ZodType<RawRecord> {
  const shape = Object.fromEntries(
    COLLECTION_FIELDS[collection].map((field) => [field, getFieldSchema(collection, field)]),
  );
  return z.object(shape).strict();
}

const RECORD_SCHEMAS = Object.fromEntries(
  CATALOG_COLLECTIONS.map((collection) => [collection, createRecordSchema(collection)]),
) as Readonly<Record<CatalogCollection, ZodType<RawRecord>>>;

function getRecordIdentity(value: unknown): {
  readonly name?: string | undefined;
  readonly source?: string | undefined;
} {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return {};
  const record = value as Record<string, unknown>;
  return {
    name: typeof record.name === 'string' ? record.name : undefined,
    source: typeof record.source === 'string' ? record.source : undefined,
  };
}

export function validateCollectionRecords(
  file: string,
  collection: CatalogCollection,
  value: unknown,
): readonly RawRecord[] {
  const recordsResult = z.array(RECORD_SCHEMAS[collection]).safeParse(value);
  if (recordsResult.success) return value as readonly RawRecord[];

  const failures = recordsResult.error.issues.flatMap((issue) => {
    const record = getRecordIdentity(Array.isArray(value) ? value[issue.path[0] as number] : undefined);
    const paths = issue.code === 'unrecognized_keys' ? issue.keys.map((key) => [...issue.path, key]) : [issue.path];
    return paths.map((path) => ({
      collection,
      file,
      message: issue.message,
      path,
      recordName: record.name,
      recordSource: record.source,
    }));
  });
  throw new ValidationError(failures);
}

export function validateCollectionFile(
  file: string,
  value: unknown,
  collections: readonly CatalogCollection[],
  collectionNames: readonly string[] = collections,
  allowedCollections: readonly string[] = collections,
): Readonly<Record<CatalogCollection, readonly RawRecord[] | undefined>> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new ValidationError(
      collections.map((collection) => ({ collection, file, message: 'Expected a JSON object.', path: [] })),
    );
  }
  const fileValue = value as Record<string, unknown>;
  const allowedKeys = new Set(['_meta', ...allowedCollections]);
  const unknownKeys = Object.keys(fileValue).filter((key) => !allowedKeys.has(key));
  if (unknownKeys.length > 0) {
    throw new ValidationError(
      unknownKeys.map((key) => ({
        collection: collections[0]!,
        file,
        message: 'Unrecognized top-level collection.',
        path: [key],
      })),
    );
  }
  const missingCollections = collections.flatMap((collection, index) =>
    fileValue[collectionNames[index]!] === undefined ? [{ collection, name: collectionNames[index]! }] : [],
  );
  if (missingCollections.length > 0) {
    throw new ValidationError(
      missingCollections.map(({ collection, name }) => ({
        collection,
        file,
        message: 'Required collection is missing.',
        path: [name],
      })),
    );
  }

  return Object.fromEntries(
    collections.map((collection, index) => [
      collection,
      validateCollectionRecords(file, collection, fileValue[collectionNames[index]!]),
    ]),
  ) as Readonly<Record<CatalogCollection, readonly RawRecord[] | undefined>>;
}

export function validateCatalogProjectRoot(projectRoot: string, sourceRoot = DEFAULT_SOURCE_ROOT): ValidationResult {
  const manifest = createCatalogManifest(projectRoot, sourceRoot);
  const files: string[] = [];

  for (const file of manifest.files) {
    if (file.role !== 'entity') continue;

    const value: unknown = JSON.parse(readFileSync(join(projectRoot, file.path), 'utf8'));
    const entityCollections = file.collections.filter((collection) => collection.domain !== undefined);
    const collections = entityCollections.map((collection) => collection.domain!);
    validateCollectionFile(
      file.path,
      value,
      collections,
      entityCollections.map((collection) => collection.name),
      file.collections.map((collection) => collection.name),
    );
    files.push(file.path);
  }

  return { files };
}
